### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by maacl** [kennytilton/rube#1]
Any hints on how to run this?

I tried `lein cljsbuild once` and then opening `rube/resources/identica/source/index`, but that results in a ton of missing files eg.

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/mac/Dropbox/opt/qooxdoo-5.0.1-sdk/framework/source/class/qx/util/OOUtil.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/mac/Dropbox/opt/qooxdoo-5.0.1-sdk/framework/source/class/qx/core/Environment.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/mac/Dropbox/opt/qooxdoo-5.0.1-sdk/framework/source/class/qx/bom/client/EcmaScript.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/mac/Dropbox/opt/qooxdoo-5.0.1-sdk/framework/source/class/qx/lang/normalize/Function.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///Users/mac/Dropbox/opt/qooxdoo-5.0.1-sdk/framework/source/class/qx/lang/normalize/Array.js Failed to load resource: net::ERR_FILE_NOT_FOUND
...
```

**Comment by kennytilton** [comment]
My apologies for not properly testing.

I have now fixed things up and tested by cloning onto an unrelated system, 

But a change is required: open rube/resources/identica/build/index.html (emphasis on "build") instead of the one in the source sub-directory. (That one might work if one had qooxdoo installed in the path where you see it looking, but that was not my intention.)

This week I plan to really flesh this thing out and add some proper doc (and test better). In the interim I may well push broken versions. Hmm, I will tag tested commits so folks have fallbacks. Their names will say as much.

**Comment by kennytilton** [comment]
ps. And now there is no need for lein cljsbuild once, I will go improve the readme.

pps. the resources sub-directory (but not the qx project) has been renamed identica->helloworld

**Comment by maacl** [comment]
Thanks for this. I assume the path is
`rube/resources/helloworld/build/index.html` ?

**Comment by kennytilton** [comment]
Oops again. Yes, I renamed the directory to be more in line with the code underneath. I did not rename the nested identica directory because that name gets baked into the code by the qooxdoo project generator. I will get this all straightened out by the official release this weeknend. I am adding a few notes to the readme btw.

**Comment by maacl** [comment]
Thanks.

**Comment by kennytilton** [comment]
I want to give you a heads up that in my next commit I am switching it back from helloworld to identica after getting into a struggle with qooxdoo over how it finds pngs etc -- the name was baked in deeper than I realized.

**Comment by maacl** [comment]
Thanks, no problem.
